# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-09-15T22:33:36+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import agent

app = FastAPI(
    title='Agent Protocol',
    description='Specification of the API protocol for communication with an agent.',
    version='v0.4',
    servers=[{'url': 'http://0.0.0.0:8000', 'description': 'Test server'}],
)

app.include_router(agent.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
